added new features

diff --git a/emagnet b/emagnet
--- a/emagnet
+++ b/emagnet
@@ -119,7 +119,7 @@ if [[ -z $TIME ]]; then
  if [[ -n $timepastebin ]];then sed -i '19d' /etc/emagnet.conf;sed -i "19i TIME=" /etc/emagnet.conf;
     sed -i "s/TIME=/TIME=$timepastebin/g" /etc/emagnet.conf;printf "Refresh time has been set to: $timepastebin seconds"
    echo "\[$(date +%d/%m/%Y\ -\ %H:%M)\]: $(whoami) - Aborted for safety, don't use your own IP!!" >> $EMAGNETLOGS/emagnet.log
- else 
+ else
     sed -i '19d' /etc/emagnet.conf;
     sed -i "19i TIME=" /etc/emagnet.conf;
     sed -i "s/TIME=/TIME=10/g" /etc/emagnet.conf
@@ -318,7 +318,7 @@ emagnet2() {
 # Download all urls from pastebin via elinks or lynx, emagnet-setup handle this                #
 lynx -dump $PASTEBIN | sed "s/com\//com\/raw\//g" | grep -o http.* | sed -n "7,14p" > /tmp/.emagnet
 grep -q security /tmp/.emagnet
-if [[ $? = "0" ]]; then
+if [[ $(grep -q security /tmp/.emagnet; echo $?) = "0" ]]; then
   printf "Pastebin.com asking emagnet for accept the re-captcha.\n\n"
   printf "Open your browser, go to https://pastebin.com and enter the re-captcha\n"
   printf "and then you will be able to continue, if this wont help - Wait for a while\n\n"
@@ -522,6 +522,47 @@ copy_files
 merge_logs
 }
 
+
+
+fetchurls() {
+while :; do
+curl -Ls https://pastebin.com|grep -o -E 'href="([^"#]+)"' | cut -d'"' -f2|grep archive -A10 | sed -n 2,9p|sed 's/^/http:\/\/pastebin.com\/raw/g' >> /tmp/.emagnet-urls
+while read line; do wget -q \$line; done < /tmp/.emagnet
+clear 
+banner
+printf "%29sURLS: [\e[1;32m$(cat /tmp/.emagnet-urls|wc -l)\e[0m]\n"
+sleep 10
+done
+}
+
+downloadfetchedurls() {
+if [[ -f /tmp/.emagnet-urls ]]; then
+clear
+banner
+printf "Please wait, downloading \e[1;32m$(cat /tmp/.emagnet-urls | wc -l)\e[0m uploads from pastebin.com"
+parallel -j $THREADS wget -nc -q -P $EMAGNETTEMP {} < /tmp/.emagnet-urls &> /dev/null
+printf "...[\e[1;32mDONE\e[0m]\n\n"
+rm /tmp/.emagnet-urls
+else
+banner
+echo -e "You must fetch some urls before you can download uploads from pastebin."
+read -p "Do you want me to fetch some downloads for you (y/N): " fetchdownloads
+case $fetchdownloads in
+     y) fetchdownloads ;;
+     *) echo "Aborted."; exit ;;
+esac
+exit
+fi
+rm /tmp/.emagnet-urls &> /dev/null && rm /tmp/.emagnet &> /dev/null
+}
+
+
+
+
+
+
+
+
 ######################################################################
 #### Check so everything is OK before we running emagnet........:.####
 ######################################################################
@@ -536,8 +577,10 @@ checkeverything
 ######################################################################
 #### Getopts for emagnet........................................:.####
 ######################################################################
-while getopts ":abcemnkhHpsSvumq" getopt; do
+while getopts ":abcemnkhHpsSvumqfd" getopt; do
   case $getopt in
+       d) downloadfetchedurls ;; # New
+       f) fetchurls ;; # new
        m) mergeem ;;
        e|\-emagnet)
 
